version: '3.9'
services:
  postgres:
    container_name: postgresdb
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: soubhik
      POSTGRES_PASSWORD: soubhik
      POSTGRES_DB: distributed_chat_app
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql
